---
title: "Final Project"
author: "Group 6"
date: "2024-12-06"
output: html_document
---

# Introduction 


#probably put pictures of each of the amphibians in the intro 

```{r, libraries, include=FALSE}
library(rnaturalearth)
library(sf)
library(tidyverse)
library(dplyr)
library(stars)
library(randomForest)
library(mapview)
library(ggplot2)
library(parallel)
library(gridExtra)
```

<center>
  **Figure 1:** Map of Towns of Interest in NH 
</center>

```{r, plot of NH, fig.cap = "Map of NH with towns that amphibian data was collected from."}

nh <- read_sf("NH/New_Hampshire_Political_Boundaries.shp") %>%
  rename(TOWN=pbpNAME) 

towns_of_interest <- c("Hancock", "Nelson", "Peterborough", "Keene")

nh_filtered <- nh %>% filter(TOWN %in% towns_of_interest)

ggplot() +
  geom_sf(data = nh, fill = "gray80", color = "black", lwd = 0.1) +  # Background towns
  geom_sf(data = nh_filtered, fill = "red", color = "black", lwd = 0.5) +  # Highlight towns of interest
  geom_sf_text(data = nh_filtered, aes(label = TOWN), size = 3, color = "black") +  # Label towns of interest
  theme_void()
```




# Methods 



```{r, load the data, warning=F, echo = F, message = F}
amphibian <- read_csv("amphibiandata.csv")
amphibian <- amphibian %>%
  rename(Dead = `# Dead`) %>% 
  rename(Crossed = `# Crossed`) %>% 
  rename(TOWN = `Town`) %>% 
  rename(year = `Year`)

nh_amphibian <- nh_filtered %>% 
  left_join(amphibian, by ="TOWN") %>% 
  dplyr::select(TOWN, Dead, geometry)
```

```{r, raster data, message = F, warning=F, echo = F}
#raster data:
f <- list.files("NLCD",pattern = ".tif", full.names=TRUE)
print(f)

lndcov <- f[grepl("LndCov", f)]
new_lndcov <- gsub(".*LndCov_([0-9]{4}).*", "\\1", basename(lndcov))

#land use
read_stars2 <- function(x, dat = NULL, name = NULL) {
  x %>% 
    read_stars(f[grepl(dat, f)]) %>%
    setNames(name) %>%
    st_transform(st_crs(nh)) %>%
    st_crop(nh)
}

#use lapply to load each file of each dataset
lu <- lapply(f[grepl("LndCov", f)], function(x) read_stars2(x, "LndCov", "landuse"))
names(lu) <- new_lndcov
```


```{r, analysis}

lu_legend <- read_csv("NLCD/NLCD_landcover_legend_2018_12_17_cFIMZEB3BFBhJA54WRx4.csv") %>% 
  rename(landuse=Value) %>% 
  mutate(landuse=as.factor(landuse))

dev <- (lu_legend %>% filter(!is.na(Legend)))[4:7,]$Legend

join_dat <- function(x){
  x %>% st_as_sf %>% 
    st_join(nh_filtered) %>% 
    st_drop_geometry() %>% 
    as_data_frame() %>% 
    left_join(lu_legend) %>% 
    dplyr::select(landuse, TOWN,Legend) %>% 
    group_by(landuse,TOWN,Legend) %>% 
    dplyr::filter(Legend%in%dev) %>% 
    count
  
}

nh_lu <- lapply(1:length(lu), function(y) {
  join_dat(lu[[y]]) %>% mutate(year = names(lu)[y]) 
})

nh_lu_combined <- bind_rows(nh_lu)
nh_lu_combined <- nh_lu_combined %>% 
  filter(!is.na(TOWN), !is.na(Legend))


#Use this for a custom function to pull development index for each year and town
dev_index_result <- nh_lu_combined %>% 
  na.omit %>% 
  group_by(TOWN,year) %>% 
  mutate(dev_prop=n/sum(n)) %>% 
  left_join(
    tibble(Legend=dev,score=1:4)
  ) %>% 
  group_by(TOWN,year) %>% 
  summarize(dev_index=log(sum(dev_prop*score))) #development index

#FINAL TIBBLE!!!
combined_data <- dev_index_result %>%
  left_join(amphibian, by = c("TOWN", "year")) %>% 
  na.omit
```




# Results 

```{r, working data, message = F, warning=F, echo = F}
# Is amphibian abundance spaitally autocorrelated, are there pockets of higher or lower dead??

nh_amphibian %>%
  ggplot() + 
  geom_sf(aes(fill = Dead)) +
  labs(title = "Amphibian Abundance (Dead) Across New Hampshire") +
  scale_fill_gradient(
    name = "Count of Dead Amphibians", 
    limits = c(0, 150), 
    low = "lightblue", 
    high = "darkblue", 
    na.value = "grey50"
  ) +
  theme_minimal()

mapview(nh_amphibian, zcol="Dead")
```


```{r, mortality rate, message = F, echo = F, warning=F}
combined_data %>%
  ggplot(aes(x = year, y = Dead / Crossed, color = Species)) +
  geom_line() +
  labs(title = "Amphibian Mortality Rates Over Time", 
       x = "Year", y = "Mortality Rate") +
  theme_minimal()
```



```{r, random forest model, message = F, echo = F, warning=F}
rf_model <- randomForest(Crossed ~ dev_index + year + TOWN + Species, data = combined_data, importance = TRUE)
importance(rf_model)
varImpPlot(rf_model)
```



```{r, analyze results linear models, message = F, echo = F, warning=F}
#linear model: 
#testing the relationship between amphibian crossings (Crossed) and the development index (dev_index), year, and town (TOWN).
lm_result <- lm(Crossed ~ dev_index + year + TOWN, data = combined_data)
summary(lm_result)

#interaction between development index and year 
#an interaction term would indicate that the development index's effect is stronger or weaker depending on the year
lm_result_interaction <- lm(Crossed ~ dev_index * year + TOWN, data = combined_data)
summary(lm_result_interaction)
ggplot(combined_data, aes(x = year, y = Crossed, color = dev_index)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = dev_index)) +
  labs(title = "Effect of Development Index Over Time on Amphibian Crossings", 
       x = "Year", y = "Number of Crossed Amphibians")
```


```{r, graphing, message = F, echo = F, warning=F}
plot_keene <- ggplot(subset(combined_data, TOWN == "Keene"), aes(x = year, y = dev_index)) +
  geom_point(aes(color = TOWN), size = 3) +
  geom_line(aes(group = TOWN, color = TOWN), size = 1) +
  labs(title = "Keene", x = "Year", y = "Development Index") +
  theme_minimal()



plot_hancock <- ggplot(subset(combined_data, TOWN == "Hancock"), aes(x = year, y = dev_index)) +
  geom_point(aes(color = TOWN), size = 3) +
  geom_line(aes(group = TOWN, color = TOWN), size = 1) +
  labs(title = "Hancock", x = "Year", y = "Development Index") +
  theme_minimal()

plot_nelson <- ggplot(subset(combined_data, TOWN == "Nelson"), aes(x = year, y = dev_index)) +
  geom_point(aes(color = TOWN), size = 3) +
  geom_line(aes(group = TOWN, color = TOWN), size = 1) +
  labs(title = "Nelson", x = "Year", y = "Development Index") +
  theme_minimal()

plot_peterborough <- ggplot(subset(combined_data, TOWN == "Peterborough"), aes(x = year, y = dev_index)) +
  geom_point(aes(color = TOWN), size = 3) +
  geom_line(aes(group = TOWN, color = TOWN), size = 1) +
  labs(title = "Peterborough", x = "Year", y = "Development Index") +
  theme_minimal()

grid.arrange(plot_keene, plot_hancock, plot_nelson, plot_peterborough, ncol = 2)
```

